GET http://localhost:3001/api/notes HTTP/1.1

###
GET http://localhost:3001/api/notes/3 HTTP/1.1

### 
DELETE http://localhost:3001/api/notes/4 HTTP/1.1

###
POST http://localhost:3001/api/notes HTTP/1.1 
content-Type: application/json

{
  "content": "GET and POST are the most important methods of HTTP protocol",
  "important": true
}

### 
POST http://localhost:3001/api/notes HTTP/1.1 
content-Type: application/json

{
  "important": true
}